workflows:
  flutter-build:
    name: Build Weather App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build Android APK
        script: flutter build apk --release

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - eseyfullayev51@gmail.com
