workflows:
  ios-only:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_NAME: 1.0.0
        BUILD_NUMBER: 1
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS (No Code Sign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - eseyfullayev51@gmail.com
